name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.4
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run biome fix
        run: pnpm run biome:fix

      - name: Run linter
        run: pnpm run lint
        
      - name: Build project
        run: pnpm run build
